Dark theme support
mabhub/makina-presences pull request #32
Opened 2022-04-04 20:56 UTC by Bo-Duke

Ajout d'un thème sombre ainsi qu'un menu utilisateur pour contrôler l'affichage de ce thème (trois options possibles : Sombre, Clair ou bien suivre le thème système).

Par défaut si l'utilisateur n'a pas de préférence, on estime qu'il veut le thème "Système". Le choix du thème est stocké dans le local storage.

L'affichage du plan inverse simplement les couleurs pour avoir le thème sombre, ça marche bien sur le cas présent mais c'est à prendre en compte dans le cas de contributions avec d'autres plans.

2022-04-04 20:58 UTC, Bo-Duke commented on src/main.jsx
> +    }
Si on veut que le thème par défaut soit plutôt le "clair" pour ne pas changer les habitudes, il faut remplacer ici : 

```suggestion
    if (themePrefs === "dark") {
      setCurrentTheme('dark');
    } else if (themePrefs === 'light') {
      setCurrentTheme('light');
    } else if (themePrefs === 'system') {
      setCurrentTheme(prefersDarkMode ? 'dark' : 'light');
    } else {
      setThemePrefs('light');
    }
```

2022-04-05 16:36 UTC, mabhub requested changes
Good job!
But do not forget checking linting!

2022-04-05 16:36 UTC, mabhub commented on src/components/UserMenu.jsx
> +      fill: theme.palette.mode === 'dark' ? 'white' : 'black',
```suggestion
      fill: 'currentColor',
```

2022-04-05 16:36 UTC, mabhub commented on src/main.jsx
> +function App() {
```suggestion
const App = () => {
```

2022-04-05 16:36 UTC, mabhub commented on src/main.jsx
> +      setThemePrefs('system');
Maybe check using a default value for `usePersistedState`…?

2022-04-05 16:36 UTC, mabhub commented on src/main.jsx
> +  <App />,
Maybe find another component name, and also keep `React.StrictMode` at top level.

2022-04-15 20:48 UTC, mabhub approved these changes

2022-04-15 20:48 UTC, merged